# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-07 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=b'bde22040-ec8a-4e14-bfa3-24f4b08fa2a2', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=1024)),
                ('middle_name', models.CharField(max_length=1024)),
                ('last_name', models.CharField(max_length=1024)),
                ('mobile', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_models.User'),
        ),
    ]
