# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-07 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'6c116284-39e0-49e0-a71e-abfe8a823e22', max_length=64, primary_key=True, serialize=False),
        ),
    ]
